# Generated by Django 3.0 on 2020-05-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
