# Generated by Django 3.0 on 2020-05-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved',
        ),
    ]
