# Generated by Django 3.0 on 2020-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_event_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='D', max_length=1),
        ),
    ]
