# Generated by Django 3.0 on 2020-06-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fest',
            name='events',
            field=models.ManyToManyField(to='core.Event'),
        ),
    ]
